# Generated by Django 5.2.7 on 2025-10-19 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('ultimo_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('grupo_articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='gestion_precios.grupoarticulo')),
            ],
        ),
        migrations.AddField(
            model_name='grupoarticulo',
            name='linea_articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='gestion_precios.lineaarticulo'),
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('canal_venta', models.CharField(choices=[('TIENDA', 'Tienda Física'), ('ECOMMERCE', 'E-Commerce'), ('MAYORISTA', 'Mayorista'), ('TELEVENTA', 'Televenta'), ('TODOS', 'Todos los Canales')], default='TODOS', max_length=20)),
                ('fecha_inicio_vigencia', models.DateField()),
                ('fecha_fin_vigencia', models.DateField(blank=True, help_text='Si es nulo, no tiene fecha de fin.', null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('PROGRAMADA', 'Programada')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precio', to='gestion_precios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_regla', models.CharField(max_length=255)),
                ('tipo_regla', models.CharField(choices=[('ESCALA_UNIDADES', 'Por Escala de Unidades'), ('MONTO_TOTAL_PEDIDO', 'Por Monto Total del Pedido'), ('COMBINACION_PRODUCTOS', 'Por Combinación de Productos')], max_length=30)),
                ('tipo_ajuste', models.CharField(choices=[('PORCENTAJE_DSCTO', 'Porcentaje de Descuento'), ('MONTO_FIJO_DSCTO', 'Monto Fijo de Descuento'), ('PRECIO_FINAL_FIJO', 'Precio Final Fijo')], max_length=30)),
                ('valor_ajuste', models.DecimalField(decimal_places=2, help_text='El valor del descuento o precio final', max_digits=10)),
                ('min_unidades', models.PositiveIntegerField(blank=True, help_text="Para 'ESCALA_UNIDADES'", null=True)),
                ('max_unidades', models.PositiveIntegerField(blank=True, help_text="Para 'ESCALA_UNIDADES'", null=True)),
                ('min_monto_pedido', models.DecimalField(blank=True, decimal_places=2, help_text="Para 'MONTO_TOTAL_PEDIDO'", max_digits=12, null=True)),
                ('prioridad', models.PositiveIntegerField(default=10, help_text='Menor número = mayor prioridad de aplicación')),
                ('articulo_condicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_condicion', to='gestion_precios.articulo')),
                ('grupo_articulo_condicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_condicion', to='gestion_precios.grupoarticulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='gestion_precios.listaprecio')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='gestion_precios.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Si es nulo, aplica a toda la empresa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas_precio', to='gestion_precios.sucursal'),
        ),
        migrations.CreateModel(
            name='PrecioArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_en_listas', to='gestion_precios.articulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_articulos', to='gestion_precios.listaprecio')),
            ],
            options={
                'unique_together': {('lista_precio', 'articulo')},
            },
        ),
    ]
